apiVersion: v1
kind: ServiceAccount
metadata:
  name: alert-middleware-sa
  namespace: alert-middleware
  labels:
    app.kubernetes.io/name: alert-correlation-middleware
    app.kubernetes.io/component: app
automountServiceAccountToken: false
