apiVersion: v2
name: my-nginx
description: A complete Nginx Helm chart with deployment, service & ingress
type: application
version: 1.0.0
appVersion: "1.27.0"
keywords:
  - nginx
  - webserver
  - http
