{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alert-middleware.fullname" . }}-secrets
  labels:
    {{- include "alert-middleware.labels" . | nindent 4 }}
type: Opaque
data:
  SLACK_BOT_TOKEN: {{ .Values.secrets.slackBotToken | b64enc | quote }}
  {{- if .Values.secrets.webhookSecret }}
  WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | b64enc | quote }}
  {{- end }}
{{- end }}
