apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multi-env-app.fullname" . }}
  labels:
    {{- include "multi-env-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "multi-env-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "multi-env-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "multi-env-app.fullname" . }}-config
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
