apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-main-config
  labels:
    app: {{ .Values.appName }}
data:
  status: "deployed"
  message: "This is the main resource (not a hook)"
